[package]
name = "just-auth"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_urlencoded = "0.7"
serde_with = "3.9"
async-trait = "0.1"
derive_builder = "0.20"
thiserror = "1.0"
